[versions]
agp = "9.2.1"
coreKtx = "1.10.1"
appcompat = "1.6.1"
material = "1.14.0"
activityKtx = "1.8.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
appUpdate = "2.1.0"
playServicesAds = "25.4.0"
userMessaging = "4.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
play-app-update = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "appUpdate" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
user-messaging-platform = { group = "com.google.android.ump", name = "user-messaging-platform", version.ref = "userMessaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
